version: '3'

services:
  mysql:
    container_name: mysql_5
    image: mysql:5.6
    volumes:
      - "/srv/dev-disk-by-label-data/docker-container/mysql_data:/var/lib/mysql"
    expose:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD: zblj1211
      - MYSQL_DATABASE: djangodocker
      - MYSQL_USER: python
      - MYSQL_PASSWORD: python-pass

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./web/staticfiles:/django_static
    ports:
      - "8088:80"
    depends_on:
      - web

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: always

  web:
    build: ./web
    # command: python manage.py runserver 0:8000
    # ports:
    #   - "8000:8000"
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./web:/web
    expose:
      - "8000"
    depends_on:
      - mysql
      - redis

  celery:
    build: ./web
    command: celery -A web worker -l info
    volumes:
      - ./web:/web
    depends_on:
      - mysql
      - redis